### ISSUE TITLE
全量导入聊天记录只有最新的2个月

### ISSUE THREAD

**Issue by nobody-cheng** [git-jiadong/wechatDataBackup#1]
感谢up
全量导入发现只有2个月 的跨度，个人和群信息均是如此，微信上共计55G，聊天迁移后本地44G大小
iPhone13pm，win10系统
![image](https://github.com/user-attachments/assets/deb302c5-b265-40d3-ba62-8e398804ee98)
![image](https://github.com/user-attachments/assets/017d6fe1-76c8-4119-bd4d-b90d4a3f108b)

**Comment by git-jiadong** [comment]
你迁移以后先退出重新登陆一次微信，然后再导出，刚迁移过来可能有些数据没有回写到磁盘，

**Comment by nobody-cheng** [comment]
> 你迁移以后先退出重新登陆一次微信，然后再导出，刚迁移过来可能有些数据没有回写到磁盘，

wechatDataBackup.exe 和 微信 都退出重新进，然后全量、增量也重新导了一次，还是只有两个月的

**Comment by git-jiadong** [comment]
> > 你迁移以后先退出重新登陆一次微信，然后再导出，刚迁移过来可能有些数据没有回写到磁盘，
> 
> wechatDataBackup.exe 和 微信 都退出重新进，然后全量、增量也重新导了一次，还是只有两个月的

我刚刚自己测试一下和你类似的操作，迁移之后重新登陆微信再导出数据都是正常的。
你wechatDataBackup只有两个月的消息，你迁移后在PC微信上面两个月前的消息显示都是正常的吗？
可以添加我的vx：whatsapp_ultra 我需要你本地环境才能查出问题

**Comment by nobody-cheng** [comment]
> > > 你迁移以后先退出重新登陆一次微信，然后再导出，刚迁移过来可能有些数据没有回写到磁盘，
> > 
> > 
> > wechatDataBackup.exe 和 微信 都退出重新进，然后全量、增量也重新导了一次，还是只有两个月的
> 
> 我刚刚自己测试一下和你类似的操作，迁移之后重新登陆微信再导出数据都是正常的。 你wechatDataBackup只有两个月的消息，你迁移后在PC微信上面两个月前的消息显示都是正常的吗？ 可以添加我的vx：whatsapp_ultra 我需要你本地环境才能查出问题

----------------------- 分割线 ------------------
![image](https://github.com/user-attachments/assets/693ed9ec-6b31-4a4c-87ee-8b7fffcde7fa)
这是pc微信上同一个联系人是8月开始的记录（习惯删除电脑聊天）
然后将该联系人的所有记录导出备份，使用 wechatDataBackup 全量导入后 同样是原始pc微信上的时间记录
![image](https://github.com/user-attachments/assets/0c45abc2-908a-4e95-97bc-a8bc2ffbe4a4)

**Comment by git-jiadong** [comment]
> > > > 你迁移以后先退出重新登陆一次微信，然后再导出，刚迁移过来可能有些数据没有回写到磁盘，
> > > 
> > > 
> > > wechatDataBackup.exe 和 微信 都退出重新进，然后全量、增量也重新导了一次，还是只有两个月的
> > 
> > 我刚刚自己测试一下和你类似的操作，迁移之后重新登陆微信再导出数据都是正常的。 你wechatDataBackup只有两个月的消息，你迁移后在PC微信上面两个月前的消息显示都是正常的吗？ 可以添加我的vx：whatsapp_ultra 我需要你本地环境才能查出问题
> 
> ----------------------- 分割线 ------------------
> ![image](https://github.com/user-attachments/assets/693ed9ec-6b31-4a4c-87ee-8b7fffcde7fa)
> 这是pc微信上同一个联系人是8月开始的记录（习惯删除电脑聊天）
> 然后将该联系人的所有记录导出备份，使用 wechatDataBackup 全量导入后 同样是原始pc微信上的时间记录
> ![image](https://github.com/user-attachments/assets/0c45abc2-908a-4e95-97bc-a8bc2ffbe4a4)
> 
> 

这样子看导出是正常的，你PC微信的记录是什么样子，导出就是什么样子。
还有如果你用的是备份功能把记录备份到电脑，PC微信是看不到你备份那些记录的。要PC微信和手机记录保持一致应该使用迁移功能

**Comment by nobody-cheng** [comment]
> > > > > 你迁移以后先退出重新登陆一次微信，然后再导出，刚迁移过来可能有些数据没有回写到磁盘，
> > > > 
> > > > 
> > > > wechatDataBackup.exe 和 微信 都退出重新进，然后全量、增量也重新导了一次，还是只有两个月的
> > > 
> > > 
> > > 我刚刚自己测试一下和你类似的操作，迁移之后重新登陆微信再导出数据都是正常的。 你wechatDataBackup只有两个月的消息，你迁移后在PC微信上面两个月前的消息显示都是正常的吗？ 可以添加我的vx：whatsapp_ultra 我需要你本地环境才能查出问题
> > 
> > 
> > ----------------------- 分割线 ------------------
> > ![image](https://private-user-images.githubusercontent.com/34908468/370230896-693ed9ec-6b31-4a4c-87ee-8b7fffcde7fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzM0NjIsIm5iZiI6MTcyNzE3MzE2MiwicGF0aCI6Ii8zNDkwODQ2OC8zNzAyMzA4OTYtNjkzZWQ5ZWMtNmIzMS00YTRjLTg3ZWUtOGI3ZmZmY2RlN2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEwMTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZTFhYzE2MTBiYmVmNTFiMThhNmIyZDk0ZDY5ODgyMGM0NTFmNmE5MTQyMTdkNmM3ZjE0Y2U0YzZiNTk2YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QAo90Eu2zyD4mJscLux77rxMpVuUXGAfw6yZyd10IkE)
> > 这是pc微信上同一个联系人是8月开始的记录（习惯删除电脑聊天）
> > 然后将该联系人的所有记录导出备份，使用 wechatDataBackup 全量导入后 同样是原始pc微信上的时间记录
> > ![image](https://private-user-images.githubusercontent.com/34908468/370231888-0c45abc2-908a-4e95-97bc-a8bc2ffbe4a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzM0NjIsIm5iZiI6MTcyNzE3MzE2MiwicGF0aCI6Ii8zNDkwODQ2OC8zNzAyMzE4ODgtMGM0NWFiYzItOTA4YS00ZTk1LTk3YmMtYThiYzJmZmJlNGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEwMTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MTZjOTVhYjQ1NTZiNTQ4ZTYyOThmMDM3OGU4MmUyNTcwZGVkZTI5ZDhiZGVlODZhNjRmNjRhMDFjMTkxZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5u3T3-F17kigjwwNF2PFC5agvbZOZm8QsvW7C81paaE)
> 
> 这样子看导出是正常的，你PC微信的记录是什么样子，导出就是什么样子。 还有如果你用的是备份功能把记录备份到电脑，PC微信是看不到你备份那些记录的。要PC微信和手机记录保持一致应该使用迁移功能

试了一下迁移确实可以，那微信备份到电脑后使用这个 wechatDataBackup 查看的是怎么用法？-->>不使用官方微信也可以进行查看？

**Comment by git-jiadong** [comment]
> > > > > > 你迁移以后先退出重新登陆一次微信，然后再导出，刚迁移过来可能有些数据没有回写到磁盘，
> > > > > 
> > > > > 
> > > > > wechatDataBackup.exe 和 微信 都退出重新进，然后全量、增量也重新导了一次，还是只有两个月的
> > > > 
> > > > 
> > > > 我刚刚自己测试一下和你类似的操作，迁移之后重新登陆微信再导出数据都是正常的。 你wechatDataBackup只有两个月的消息，你迁移后在PC微信上面两个月前的消息显示都是正常的吗？ 可以添加我的vx：whatsapp_ultra 我需要你本地环境才能查出问题
> > > 
> > > 
> > > ----------------------- 分割线 ------------------
> > > ![image](https://private-user-images.githubusercontent.com/34908468/370230896-693ed9ec-6b31-4a4c-87ee-8b7fffcde7fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzM0NjIsIm5iZiI6MTcyNzE3MzE2MiwicGF0aCI6Ii8zNDkwODQ2OC8zNzAyMzA4OTYtNjkzZWQ5ZWMtNmIzMS00YTRjLTg3ZWUtOGI3ZmZmY2RlN2ZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEwMTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZTFhYzE2MTBiYmVmNTFiMThhNmIyZDk0ZDY5ODgyMGM0NTFmNmE5MTQyMTdkNmM3ZjE0Y2U0YzZiNTk2YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QAo90Eu2zyD4mJscLux77rxMpVuUXGAfw6yZyd10IkE)
> > > 这是pc微信上同一个联系人是8月开始的记录（习惯删除电脑聊天）
> > > 然后将该联系人的所有记录导出备份，使用 wechatDataBackup 全量导入后 同样是原始pc微信上的时间记录
> > > ![image](https://private-user-images.githubusercontent.com/34908468/370231888-0c45abc2-908a-4e95-97bc-a8bc2ffbe4a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNzM0NjIsIm5iZiI6MTcyNzE3MzE2MiwicGF0aCI6Ii8zNDkwODQ2OC8zNzAyMzE4ODgtMGM0NWFiYzItOTA4YS00ZTk1LTk3YmMtYThiYzJmZmJlNGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEwMTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MTZjOTVhYjQ1NTZiNTQ4ZTYyOThmMDM3OGU4MmUyNTcwZGVkZTI5ZDhiZGVlODZhNjRmNjRhMDFjMTkxZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5u3T3-F17kigjwwNF2PFC5agvbZOZm8QsvW7C81paaE)
> > 
> > 这样子看导出是正常的，你PC微信的记录是什么样子，导出就是什么样子。 还有如果你用的是备份功能把记录备份到电脑，PC微信是看不到你备份那些记录的。要PC微信和手机记录保持一致应该使用迁移功能
> 
> 试了一下迁移确实可以，那微信备份到电脑后使用这个 wechatDataBackup 查看的是怎么用法？-->>不使用官方微信也可以进行查看？

是的 微信的记录都是加密的，用户只有在登陆的情况才能查看。
这个工具的作用就是让你的聊天记录脱离于微信也能正常查看。
