### ISSUE TITLE
我目前遇到一个问题，首次打开软件同步微信数据之后 wechatDataBackup 中未显示我目前实时聊天的数据信息。

### ISSUE THREAD

**Issue by BNTang** [git-jiadong/wechatDataBackup#12]

**Comment by git-jiadong** [comment]
你重启微信后再导出一次试试

**Comment by BNTang** [comment]
> 你重启微信后再导出一次试试

还是不行，刚刚试了一次。

首先是登录微信，打开该开源软件进行导出数据，wechatDataBackup 中，未展示微信中的聊天信息。

这个时候我将微信退出，wechatDataBackup 打开着，我重新上微信，导出数据依旧如此。

**Comment by git-jiadong** [comment]
> > 你重启微信后再导出一次试试
> 
> 还是不行，刚刚试了一次。
> 
> 首先是登录微信，打开该开源软件进行导出数据，wechatDataBackup 中，未展示微信中的聊天信息。
> 
> 这个时候我将微信退出，wechatDataBackup 打开着，我重新上微信，导出数据依旧如此。

没有日志我定位不了，加我vx: whatsapp_ultra 发日志给我看看

**Comment by git-jiadong** [comment]
![image](https://github.com/user-attachments/assets/14dbdba7-cdff-4da5-bca6-e993985cb967)
