### ISSUE TITLE
以管理员打开时，无法选择SMB映射的NAS硬盘

### ISSUE THREAD

**Issue by huangry999** [git-jiadong/wechatDataBackup#16]
版本：amd64, v1.0.5

非管理员权限打开，能看到nas的SMB硬盘，管理员权限打开无法看到

手动修改配置文件到SMB硬盘，**以管理员权限**启动程序后无法识别，报错Z:\file\wechatBackup:The system cannot find the path specified. 但是**以非管理员权限**启动程序，能正常启动。并且功能正常

所以临时可以手动修改配置文件到SMB硬盘，大佬看看要不要修复这个问题

**Comment by git-jiadong** [comment]
听你的描述好像是你电脑“非管理员权限”和“管理员权限”访问nas的权限问题。
你不要手动修改配置的文件情况下，软件用管理员权限启动，在wechatDataBackup设置界面修改存储路径，看能不能选到你nas的路径。如果不可能那就是正常的，是你电脑“管理员权限”没有办法访问nas

**Comment by huangry999** [comment]
用filezilla试了下也存在同样问题，就是我电脑权限的原因，感谢感谢
