### ISSUE TITLE
图片放大显示错误

### ISSUE THREAD

**Issue by FightTogether** [git-jiadong/wechatDataBackup#18]
系统：window11
版本：v1.0.5
<img width="704" alt="image" src="https://github.com/user-attachments/assets/0a33c7e0-6782-4564-9e5b-decc8c9ce408">

**Comment by git-jiadong** [comment]
这种情况是你微信上面没有点开过这张图片，微信只下载了缩略图。你微信点开这张图片后再导出试试。

**Comment by git-jiadong** [comment]
[v1.0.6](https://github.com/git-jiadong/wechatDataBackup/releases/v1.0.6) 做了更友好的交互，可以更新体检
