### ISSUE TITLE
关于增量备份的问题

### ISSUE THREAD

**Issue by e4je** [git-jiadong/wechatDataBackup#19]
在备份一次后如果不重启微信，那增量备份是不会有最新的数据的，需要把微信退出重新打开增量才会增量到目前最新的数据。

**Comment by git-jiadong** [comment]
> 在备份一次后如果不重启微信，那增量备份是不会有最新的数据的，需要把微信退出重新打开增量才会增量到目前最新的数据。
这个问题目前不算是bug，wechatDataBackup导出的数据是读取硬盘上数据库的，而微信中新收到的信息或者是你刚备份的数据，并不会立马全部回写到硬盘的数据库里面，有可能部分数据还存在文件系统的缓存中脏页中，或者微信程序中还有一道缓存，才到硬盘的数据库中。
目前只能通过重启微信的这个办法强制让数据全部保存到硬盘，这样子我们导出数据才是全的。
或许后面研究一下怎么触发系统的脏页回写，可能能省略掉重启微信的这个动作，后面有时间我研究一下。

**Comment by e4je** [comment]
感谢大佬解答，顺便想问问这个导出备份后续会考虑在将数据还原回微信的功能么

**Comment by git-jiadong** [comment]
> 感谢大佬解答，顺便想问问这个导出备份后续会考虑在将数据还原回微信的功能么

不会的，还原回去属于篡改微信的数据了，这个风险很大，有问题担不起
