### ISSUE TITLE
微信双开只能导出一个号的

### ISSUE THREAD

**Issue by Fe5O6** [git-jiadong/wechatDataBackup#2]
我发现电脑双开微信只能导出一个号的，而且不能切换账号

**Comment by git-jiadong** [comment]
是的 目前还没有支持多账号，如果你需要备份多个账号可以把程序多复制一份在另外的路径，后续版本支持多账号后再把其中一个的备份数据拷贝回来即可

**Comment by git-jiadong** [comment]
已经在V1.0.3版本支持了双开导出，和多账号切换的功能
