### ISSUE TITLE
编译错误，undefined: Encoder, Init, Decoder, SilkInit

### ISSUE THREAD

**Issue by Sgt-Huffman** [git-jiadong/wechatDataBackup#20]
执行wails build时提示错误：
![image](https://github.com/user-attachments/assets/4f5a11e9-00d6-4c11-af67-63bfa9d8ce7c)

**Comment by git-jiadong** [comment]
> 执行wails build时提示错误：
> ![image](https://github.com/user-attachments/assets/4f5a11e9-00d6-4c11-af67-63bfa9d8ce7c)
> 

应该是你环境没有gcc导致的。
你安装一下gcc后再试试
[https://jmeubank.github.io/tdm-gcc/](https://jmeubank.github.io/tdm-gcc/)
