### ISSUE TITLE
我这个字体怎么和大家的不一样

### ISSUE THREAD

**Issue by wdy3334** [git-jiadong/wechatDataBackup#21]
![image](https://github.com/user-attachments/assets/f0bae766-da97-48c6-ad14-7a5a96246f5d)

**Comment by wdy3334** [comment]
其他软件都正常字体

**Comment by git-jiadong** [comment]
看起来像是你以前自己修改过字体导致的

**Comment by wdy3334** [comment]
> 看起来像是你以前自己修改过字体导致的

好的  感谢 我自己研究下

**Comment by git-jiadong** [comment]
@wdy3334 https://github.com/git-jiadong/wechatDataBackup/releases/tag/v1.2.2 字体显示异常在这个版本解决了
