### ISSUE TITLE
卡在80%卡了好几个小时了，咋解决啊？

### ISSUE THREAD

**Issue by AndrewChenVIP** [git-jiadong/wechatDataBackup#3]
2024/09/13 15:51:13.532931 app.go:133: {"status":"processing", "result":"export WeChat voice doing", "progress": 80}
2024/09/13 15:51:14.533975 app.go:133: {"status":"processing", "result":"export WeChat voice doing", "progress": 80}
2024/09/13 15:51:15.534082 app.go:133: {"status":"processing", "result":"export WeChat voice doing", "progress": 80}
2024/09/13 15:51:16.534644 app.go:133: {"status":"processing", "result":"export WeChat voice doing", "progress": 80}
2024/09/13 15:51:17.535707 app.go:133: {"status":"processing", "result":"export WeChat voice doing", "progress": 80}

日志是这样的。

**Comment by git-jiadong** [comment]
你退出程序然后再导出一次试试（可以用增量导出）

**Comment by AndrewChenVIP** [comment]
2024/09/13 16:40:16.713509 app.go:95: {"PID":95352,"FilePath":"D:\\Administrator\\Documents\\WeChat Files\\wxid_plqaektt05i822","AcountName":"wxid_plqaektt05i822","Version":"3.9.11.25","Is64Bits":true,"DBkey":"bf4f262ced044067af73ec150edc39f1c2740968dc7d4d78881fa8f07190c8a5"}
2024/09/13 16:40:18.956677 app.go:133: {"status":"processing", "result":"export WeChat DateBase start", "progress": 1}
2024/09/13 16:40:18.958283 app.go:133: {"status":"processing", "result":"export WeChat DateBase doing", "progress": 1}
2024/09/13 16:40:19.959072 app.go:133: {"status":"processing", "result":"export WeChat DateBase end", "progress": 20}
2024/09/13 16:40:19.959072 app.go:133: {"status":"processing", "result":"export WeChat Dat start", "progress": 21}
2024/09/13 16:40:19.972846 app.go:133: {"status":"processing", "result":"export WeChat Dat doing", "progress": 21}
2024/09/13 16:40:20.974073 app.go:133: {"status":"processing", "result":"export WeChat Dat end", "progress": 40}
2024/09/13 16:40:20.974073 app.go:133: {"status":"processing", "result":"export WeChat Video and File start", , "progress": 41}
2024/09/13 16:40:20.976827 wechat.go:190: VideoAndFile  93
2024/09/13 16:40:20.976827 wechat.go:196: D:\Administrator\Documents\WeChat Files\wxid_plqaektt05i822\FileStorage\Video
2024/09/13 16:40:20.976827 app.go:133: {"status":"processing", "result":"export WeChat Video and File doing", "progress": 41}
2024/09/13 16:40:20.979573 wechat.go:196: D:\Administrator\Documents\WeChat Files\wxid_plqaektt05i822\FileStorage\File
2024/09/13 16:40:20.981159 wechat.go:196: D:\Administrator\Documents\WeChat Files\wxid_plqaektt05i822\FileStorage\Cache
2024/09/13 16:40:21.977579 app.go:133: {"status":"processing", "result":"export WeChat Video and File end", "progress": 60}
2024/09/13 16:40:21.977579 app.go:133: {"status":"processing", "result":"export WeChat voice start", "progress": 61}
2024/09/13 16:40:21.977579 app.go:133: {"status":"processing", "result":"export WeChat voice doing", "progress": 61}
2024/09/13 16:40:21.980579 wechat.go:121: Query failed: no such table: Media
2024/09/13 16:40:22.977825 app.go:133: {"status":"processing", "result":"export WeChat voice doing", "progress": 80}

还是不行，日志是这样的

**Comment by git-jiadong** [comment]
你下载一个v1.0.0版本试试，可能是进度条上报阻塞了

**Comment by AndrewChenVIP** [comment]
重启了一下电脑好了……

**Comment by git-jiadong** [comment]
那应该是微信数据库有写数据还在内存没有回写到磁盘导致的
