### ISSUE TITLE
解密失败-Mac mini M1 虚拟机window11，微信版本3.9.12.17 64bits, （下面有文件）

### ISSUE THREAD

**Issue by zlfyuan** [git-jiadong/wechatDataBackup#32]
[app.log](https://github.com/user-attachments/files/18148547/app.log)

**Comment by git-jiadong** [comment]
你的电脑微信登陆的情况下，用命令行运行这个程序，再把结果贴出来看看
[wechatCheckoutKey.zip](https://github.com/user-attachments/files/18150723/wechatCheckoutKey.zip)

**Comment by zlfyuan** [comment]
[wechatCheckoutKey.log](https://github.com/user-attachments/files/18159139/wechatCheckoutKey.log)
这个是执行结果

**Comment by git-jiadong** [comment]
看日志密钥是拿到了，但你微信的路径为啥是mac的，是你修改了微信的默认存储路径吗？当前这个虚拟机里面的微信是在正常使用吗？

**Comment by zlfyuan** [comment]
没有改过路径诶，微信程序默认是在这个路径下" C:\Program Files\Tencent\WeChat>"。但是这个“UNC\Mac\Home\Documents\WeChat Files\wxid_ov3g8115xh1c12”确实存在，数据貌似都在这里。

**Comment by zlfyuan** [comment]
需要在哪个路径下面呢，我手动改下

**Comment by git-jiadong** [comment]
正常情况是要拿这个路径下的数据库去解密
"C:\Program Files\Tencent\WeChat>"
但现在拿的是这个路径下的数据库去解密
“UNC\Mac\Home\Documents\WeChat Files\wxid_ov3g8115xh1c12”
有点看不懂
你加我vx：whatsapp_ultra 
我了解一下你的环境

**Comment by git-jiadong** [comment]
最后定位到是微信修改了路径到“UNC\Mac\Home\Documents\WeChat Files\”，而访问这个新的路径需要特定权限，导致的解密失败
