### ISSUE TITLE
导出后看不到消息

### ISSUE THREAD

**Issue by lmj258** [git-jiadong/wechatDataBackup#34]
导出以后界面显示有消息，打开一片空白，导出界面退出微信重新登录再点全量导出或者增量导出都试过了，问题依旧

**Comment by lmj258** [comment]
试了下，没有实名的账号看不见消息，就像图中一样，实名过的没问题，这算是bug吗

**Comment by git-jiadong** [comment]
https://github.com/git-jiadong/wechatDataBackup/issues/23

你看一下这个

**Comment by lmj258** [comment]
> #23
> 
> 你看一下这个

没用，同一台电脑，一样的设置，同一个客户端，不同的微信，没实名的账号导出来就看不到消息，实名的没问题

**Comment by lmj258** [comment]
> 你可以把不正常的微信重新操作一次，拿份日志来看看

2024/12/19 20:24:53.082767 main.go:36: ====================== wechatDataBackup ======================
2024/12/19 20:24:53.098837 app.go:154: App version: v1.0.6
2024/12/19 20:24:53.156315 app.go:165: SetFilePrefix .\
2024/12/19 20:24:53.156315 app.go:41: SetFilePrefix .\
2024/12/19 20:24:53.156315 app.go:171: default: wxid_q0ett9ot5t5329 users: [wxid_zcidf4fdvq4722 wxid_q0ett9ot5t5329 wxid_4b1tfa1vjidb22]
2024/12/19 20:24:54.066731 app.go:320: scanAccountByPath: .\
2024/12/19 20:24:54.066731 wechat.go:924: no exist: .\\User\wxid_q0ett9ot5t5329\Msg\Misc.db
2024/12/19 20:24:54.066731 wechatDataProvider.go:229: .\\User\wxid_q0ett9ot5t5329
2024/12/19 20:24:54.067330 wechatDataProvider.go:234: CreateWechatDataProvider failed .\\User\wxid_q0ett9ot5t5329\Msg\MicroMsg.db CreateFile .\\User\wxid_q0ett9ot5t5329\Msg\MicroMsg.db: The system cannot find the path specified.
2024/12/19 20:24:54.067330 app.go:305: CreateWechatDataProvider failed: .\\User\wxid_q0ett9ot5t5329
2024/12/19 20:24:56.548359 app.go:559: utils.GetPathStat ++
2024/12/19 20:24:56.548359 app.go:561: utils.GetPathStat --
2024/12/19 20:24:56.554461 wechat.go:591: ProcessID 8600
2024/12/19 20:24:56.758793 wechat.go:790: keyAddrPtr: 0x22B0E060100
2024/12/19 20:24:56.797123 app.go:217: ProcessID 8600, FilePath E:\用户文件\文档\WeChat Files\wxid_q0ett9ot5t5329, AcountName wxid_q0ett9ot5t5329, Version 3.9.12.17, Is64Bits true
2024/12/19 20:25:01.346515 app.go:272: {"status":"processing", "result":"export WeChat DateBase start", "progress": 1}
2024/12/19 20:25:01.394292 app.go:272: {"status":"processing", "result":"export WeChat DateBase doing", "progress": 1}
2024/12/19 20:25:02.405897 wechat.go:553: WeChat DateBase report progress end
2024/12/19 20:25:02.405897 app.go:272: {"status":"processing", "result":"export WeChat DateBase end", "progress": 20}
2024/12/19 20:25:02.405897 app.go:272: {"status":"processing", "result":"export WeChat Dat start", "progress": 21}
2024/12/19 20:25:02.575607 app.go:272: {"status":"processing", "result":"export WeChat Dat doing", "progress": 21}
2024/12/19 20:25:03.576160 app.go:272: {"status":"processing", "result":"export WeChat Dat doing", "progress": 22}
2024/12/19 20:25:04.585830 app.go:272: {"status":"processing", "result":"export WeChat Dat doing", "progress": 23}
2024/12/19 20:25:05.587776 app.go:272: {"status":"processing", "result":"export WeChat Dat doing", "progress": 24}
2024/12/19 20:25:06.589450 app.go:272: {"status":"processing", "result":"export WeChat Dat doing", "progress": 25}
2024/12/19 20:25:07.589691 app.go:272: {"status":"processing", "result":"export WeChat Dat doing", "progress": 31}
2024/12/19 20:25:08.590707 app.go:272: {"status":"processing", "result":"export WeChat Dat doing", "progress": 33}
2024/12/19 20:25:09.591941 app.go:272: {"status":"processing", "result":"export WeChat Dat doing", "progress": 38}
2024/12/19 20:25:10.597195 wechat.go:468: WeChat Dat report progress end
2024/12/19 20:25:10.597195 app.go:272: {"status":"processing", "result":"export WeChat Dat end", "progress": 40}
2024/12/19 20:25:10.597879 app.go:272: {"status":"processing", "result":"export WeChat Video and File start", , "progress": 41}
2024/12/19 20:25:10.624793 wechat.go:320: VideoAndFile  40
2024/12/19 20:25:10.624793 app.go:272: {"status":"processing", "result":"export WeChat Video and File doing", "progress": 41}
2024/12/19 20:25:10.624793 wechat.go:328: E:\用户文件\文档\WeChat Files\wxid_q0ett9ot5t5329\FileStorage\Video
2024/12/19 20:25:10.634825 wechat.go:328: E:\用户文件\文档\WeChat Files\wxid_q0ett9ot5t5329\FileStorage\File
2024/12/19 20:25:10.636474 wechat.go:328: E:\用户文件\文档\WeChat Files\wxid_q0ett9ot5t5329\FileStorage\Cache
2024/12/19 20:25:11.632452 wechat.go:382: WeChat Video and File report progress end
2024/12/19 20:25:11.632452 app.go:272: {"status":"processing", "result":"export WeChat Video and File end", "progress": 60}
2024/12/19 20:25:11.633581 app.go:272: {"status":"processing", "result":"export WeChat voice start", "progress": 61}
2024/12/19 20:25:11.634740 app.go:272: {"status":"processing", "result":"export WeChat voice doing", "progress": 61}
2024/12/19 20:25:12.635791 wechat.go:290: WeChat voice report progress end
2024/12/19 20:25:12.635791 app.go:272: {"status":"processing", "result":"export WeChat voice end", "progress": 80}
2024/12/19 20:25:12.635791 app.go:272: {"status":"processing", "result":"export WeChat Head Image", "progress": 81}
2024/12/19 20:25:12.638796 wechat.go:124: ContactHeadImg1 fileNumber 11
2024/12/19 20:25:13.641433 wechat.go:178: WeChat Head Image report progress end
2024/12/19 20:25:13.641433 app.go:272: {"status":"processing", "result":"export WeChat Head Image end", "progress": 100}
2024/12/19 20:25:13.643446 app.go:453: Config File "D:\\wechat\\config.json" Already Exists
2024/12/19 20:25:26.916036 utils.go:45: getDefaultProgram Error: The system cannot find the file specified.
2024/12/19 20:25:27.246891 utils.go:83: Error executing command: exit status 1
2024/12/19 20:25:29.072583 wechat.go:930: has HeadImage
2024/12/19 20:25:29.072583 wechatDataProvider.go:229: .\\User\wxid_q0ett9ot5t5329
2024/12/19 20:25:29.080256 wechatDataProvider.go:1082: select DB startTime failed: .\\User\wxid_q0ett9ot5t5329\Msg\Multi\MSG0.db : sql: no rows in result set
2024/12/19 20:25:29.080256 wechatDataProvider.go:262: open db .\\User\wxid_q0ett9ot5t5329\Msg\Multi\MSG0.db error: sql: no rows in result set
2024/12/19 20:25:29.085491 wechatDataProvider.go:288: Contact number: 16
2024/12/19 20:25:29.085491 wechatDataProvider.go:290: resPath: .\\User\wxid_q0ett9ot5t5329
2024/12/19 20:25:29.099163 app.go:342: pageIndex: 0
2024/12/19 20:25:29.099163 app.go:349: GetWechatSessionList: 7
2024/12/19 20:25:29.125012 app.go:342: pageIndex: 1
2024/12/19 20:25:29.125012 app.go:349: GetWechatSessionList: 0
2024/12/19 20:25:29.970800 app.go:414: GetWechatMessageListByKeyWord: wxid_ck81c491jwl221 30 1720700375 
2024/12/19 20:25:29.970800 wechatDataProvider.go:596: time: 1720700375 
2024/12/19 20:25:29.970800 app.go:370: GetWechatMessageListByTime: wxid_ck81c491jwl221 30 1720700375 forward
2024/12/19 20:25:29.970800 wechatDataProvider.go:527: Not found wxid_ck81c491jwl221 1720700375 data
2024/12/19 20:25:29.970800 wechatDataProvider.go:527: Not found wxid_ck81c491jwl221 1720700375 data
2024/12/19 20:25:29.970800 wechatDataProvider.go:602: rawList.Total: 0
2024/12/19 20:25:29.970800 wechatDataProvider.go:605: user wxid_ck81c491jwl221 not find []
2024/12/19 20:25:29.970800 app.go:386: GetWechatMessageListByTime: 0
2024/12/19 20:25:29.970800 app.go:424: WeChatGetMessageListByKeyWord: 0 
2024/12/19 20:25:30.514520 app.go:414: GetWechatMessageListByKeyWord: wxid_ei5iuv6n4kzg21 30 1722707330 
2024/12/19 20:25:30.514520 wechatDataProvider.go:596: time: 1722707330 
2024/12/19 20:25:30.514520 wechatDataProvider.go:527: Not found wxid_ei5iuv6n4kzg21 1722707330 data
2024/12/19 20:25:30.514520 wechatDataProvider.go:602: rawList.Total: 0
2024/12/19 20:25:30.514520 app.go:370: GetWechatMessageListByTime: wxid_ei5iuv6n4kzg21 30 1722707330 forward
2024/12/19 20:25:30.514520 wechatDataProvider.go:527: Not found wxid_ei5iuv6n4kzg21 1722707330 data
2024/12/19 20:25:30.514520 app.go:386: GetWechatMessageListByTime: 0
2024/12/19 20:25:30.514520 wechatDataProvider.go:605: user wxid_ei5iuv6n4kzg21 not find []
2024/12/19 20:25:30.514520 app.go:424: WeChatGetMessageListByKeyWord: 0 
2024/12/19 20:25:30.928561 app.go:414: GetWechatMessageListByKeyWord: wxid_ck81c491jwl221 30 1720700375 
2024/12/19 20:25:30.928561 wechatDataProvider.go:596: time: 1720700375 
2024/12/19 20:25:30.928561 wechatDataProvider.go:527: Not found wxid_ck81c491jwl221 1720700375 data
2024/12/19 20:25:30.928561 wechatDataProvider.go:602: rawList.Total: 0
2024/12/19 20:25:30.928561 wechatDataProvider.go:605: user wxid_ck81c491jwl221 not find []
2024/12/19 20:25:30.928561 app.go:424: WeChatGetMessageListByKeyWord: 0 
2024/12/19 20:25:30.928561 app.go:370: GetWechatMessageListByTime: wxid_ck81c491jwl221 30 1720700375 forward
2024/12/19 20:25:30.928561 wechatDataProvider.go:527: Not found wxid_ck81c491jwl221 1720700375 data
2024/12/19 20:25:30.928561 app.go:386: GetWechatMessageListByTime: 0
刚刚操作的

**Comment by git-jiadong** [comment]
从日志看导出没有任何报错，就是你wxid_q0ett9ot5t5329\Msg\Multi\MSG0.db这个数据库内容是空的，你确定你这个微信在电脑上能看到记录？

**Comment by lmj258** [comment]
![微信截图_20241219214520](https://github.com/user-attachments/assets/16ff78fb-0da6-45e4-a4ec-8e152a14154f)
同一台电脑登录微信是可以看见消息的导出来看不见

**Comment by git-jiadong** [comment]
vx：whatsapp_ultra 加一下我看看你的环境
