### ISSUE TITLE
什么时候能加上自定义路径把资料存到nas里

### ISSUE THREAD

**Issue by miantiao1025** [git-jiadong/wechatDataBackup#8]
电脑空间不够~nas有空间

**Comment by git-jiadong** [comment]
> 电脑空间不够~nas有空间

有在开发了，一下版本实现

**Comment by git-jiadong** [comment]
[v1.0.4](https://github.com/git-jiadong/wechatDataBackup/releases/tag/v1.0.4) 版本已经实现自定义保存路径，你可以更新体验了
