### ISSUE TITLE
上下滑动滚动条太细，鼠标不容易选中

### ISSUE THREAD

**Issue by wc5bk6** [git-jiadong/wechatDataBackup#9]
上下滑动滚动条太细，鼠标不容易选中，容易变为拖拽，建议增大方便鼠标选中

**Comment by git-jiadong** [comment]
> 上下滑动滚动条太细，鼠标不容易选中，容易变为拖拽，建议增大方便鼠标选中

感谢反馈，我下一版本调整一下

**Comment by git-jiadong** [comment]
[v1.0.4](https://github.com/git-jiadong/wechatDataBackup/releases/tag/v1.0.4) 版本已经调整了滚动条滑块的大小，你可以更新体验了。

**Comment by wc5bk6** [comment]
非常感谢
